name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
inputs:
  bucket:
    description: 'The S3 backet name.'
    required: true
  bucket-region:
    description: 'The region of the S3 backet.'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the deployable files.'
    required: true
runs:
  using: 'node16'
  #pre: #To run before the main
  main: 'main.js' #The name of the file is not relevant 
  #post: #To run after the main